workflows:
  unit_tests:
    instance_type: mac_mini_m1
    environment:
      xcode: 14.0
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
      cancel_previous_builds: true
    scripts:
      - name: Bundle install
        script: bundle install
      - name: Pod install
        script: bundle exec pod install
      - name: Run unit tests
        script: bundle exec fastlane tests
