workflows:
  unit_tests:
    instance_type: mac_mini_m1
    environment:
      #ruby: 2.6.4
      xcode: 14.0
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
    scripts:
      - name: Bundle install
        script: bundle install
      - name: Pod install
        script: bundle exec pod install
      - name: Run unit tests
        script: bundle exec fastlane tests
